const API_BASE_URL = "https://webtechnomind.in/project/timble";
const API_ENDPOINTS = {
  LOGIN: `${API_BASE_URL}/api/login`, 
  REGISTER: `${API_BASE_URL}/api/register`,
  VERIFY_OTP: `${API_BASE_URL}/api/verify-otp`,
  PERSONAL_DETAILS: `${API_BASE_URL}/api/personal-details`,
  GET_INTERESTS_DETAILS: `${API_BASE_URL}/api/interests/details`,
  USER_PICTURE: `${API_BASE_URL}/api/user-pictures`,
  GET_USER_LIST: `${API_BASE_URL}/api/user-messages-list`,
  SEND_MESSAGE: `${API_BASE_URL}/api/send-message`,
  RECEIVE_MESSAGE: `${API_BASE_URL}/api/messages`,
  IMG_PATH: `${API_BASE_URL}/public/images`,
  PREFERENCE_GETDATA: `${API_BASE_URL}/api/your/match/preferences/details`,
  PREFERENCE_POSTDATA: `${API_BASE_URL}/api/store-user-yourmatchpreferences`,
  HOME_API_DATA: `${API_BASE_URL}/api/home-page`,
  LOGOUT: `${API_BASE_URL}/api/logout`,
  FORGOT_PASSWORD: `${API_BASE_URL}/api/forgot-password`,
  VERIFY_RESET_OTP: `${API_BASE_URL}/api/verify-reset-Otp`,
  RESET_PASSWORD: `${API_BASE_URL}/api/reset-password`,
  GET_PERSONAL_DETAILS: `${API_BASE_URL}/api/get-personal-details`,
  LIKE: `${API_BASE_URL}/api/like`,
  UNLIKE: `${API_BASE_URL}/api/unlike`,
  BASE_URL:`${API_BASE_URL}/api`,
  DELETE_IMAGE: `${API_BASE_URL}/api/user-picture/delete-image`,
  GET_USER_DETAILS: `${API_BASE_URL}/api/get-user-details`,
  ADMIN_CHANGE_PASSWORD: `${API_BASE_URL}/api/change-password`,
  GET_CUSTOMER_DETAILS: `${API_BASE_URL}/api/get-customer-details`,
};
export default API_ENDPOINTS;
